#!/bin/sh
set -e

case $1 in
    install|upgrade)
        addgroup --system gpio || true
        addgroup --system spidev || true
        addgroup --system pwm || true
        ;;
esac
    
#DEBHELPER#

exit 0